### ISSUE TITLE
Seems to be broken with Clojure 1.8

### ISSUE THREAD

**Issue by afandian** [CrossRef/heartbeat#1]
Just loading the lib doesn't work in 1.8

```
Exception in thread "main" java.lang.NoClassDefFoundError: IllegalName: compile__stub.clj_http.headers.clj-http.headers/HeaderMap, compiling:(clj_http/headers.clj:105:1)
  at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
  at clojure.lang.Compiler.analyze(Compiler.java:6669)
  at clojure.lang.Compiler.analyze(Compiler.java:6625)
  at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
  at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6319)
  at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
  at clojure.lang.Compiler.analyze(Compiler.java:6669)
  at clojure.lang.Compiler.analyze(Compiler.java:6625)
  at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
  at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
  at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
  at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
  at clojure.lang.Compiler.analyze(Compiler.java:6669)
  at clojure.lang.Compiler.eval(Compiler.java:6924)
  at clojure.lang.Compiler.eval(Compiler.java:6916)
  at clojure.lang.Compiler.load(Compiler.java:7379)
  at clojure.lang.RT.loadResourceScript(RT.java:372)
  at clojure.lang.RT.loadResourceScript(RT.java:363)
  at clojure.lang.RT.load(RT.java:453)
  at clojure.lang.RT.load(RT.java:419)
  at clojure.core$load$fn__5677.invoke(core.clj:5893)
  at clojure.core$load.invokeStatic(core.clj:5892)
  at clojure.core$load.doInvoke(core.clj:5876)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at clojure.core$load_one.invokeStatic(core.clj:5697)
  at clojure.core$load_one.invoke(core.clj:5692)
  at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
  at clojure.core$load_lib.invokeStatic(core.clj:5736)
  at clojure.core$load_lib.doInvoke(core.clj:5717)
  at clojure.lang.RestFn.applyTo(RestFn.java:142)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$load_libs.invokeStatic(core.clj:5774)
  at clojure.core$load_libs.doInvoke(core.clj:5758)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$require.invokeStatic(core.clj:5796)
  at clojure.core$require.doInvoke(core.clj:5796)
  at clojure.lang.RestFn.invoke(RestFn.java:482)
  at clj_http.core$eval3959$loading__5569__auto____3960.invoke(core.clj:1)
  at clj_http.core$eval3959.invokeStatic(core.clj:1)
  at clj_http.core$eval3959.invoke(core.clj:1)
  at clojure.lang.Compiler.eval(Compiler.java:6927)
  at clojure.lang.Compiler.eval(Compiler.java:6916)
  at clojure.lang.Compiler.load(Compiler.java:7379)
  at clojure.lang.RT.loadResourceScript(RT.java:372)
  at clojure.lang.RT.loadResourceScript(RT.java:363)
  at clojure.lang.RT.load(RT.java:453)
  at clojure.lang.RT.load(RT.java:419)
  at clojure.core$load$fn__5677.invoke(core.clj:5893)
  at clojure.core$load.invokeStatic(core.clj:5892)
  at clojure.core$load.doInvoke(core.clj:5876)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at clojure.core$load_one.invokeStatic(core.clj:5697)
  at clojure.core$load_one.invoke(core.clj:5692)
  at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
  at clojure.core$load_lib.invokeStatic(core.clj:5736)
  at clojure.core$load_lib.doInvoke(core.clj:5717)
  at clojure.lang.RestFn.applyTo(RestFn.java:142)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$load_libs.invokeStatic(core.clj:5774)
  at clojure.core$load_libs.doInvoke(core.clj:5758)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$require.invokeStatic(core.clj:5796)
  at clojure.core$require.doInvoke(core.clj:5796)
  at clojure.lang.RestFn.invoke(RestFn.java:805)
  at clj_http.client$eval3804$loading__5569__auto____3805.invoke(client.clj:1)
  at clj_http.client$eval3804.invokeStatic(client.clj:1)
  at clj_http.client$eval3804.invoke(client.clj:1)
  at clojure.lang.Compiler.eval(Compiler.java:6927)
  at clojure.lang.Compiler.eval(Compiler.java:6916)
  at clojure.lang.Compiler.load(Compiler.java:7379)
  at clojure.lang.RT.loadResourceScript(RT.java:372)
  at clojure.lang.RT.loadResourceScript(RT.java:363)
  at clojure.lang.RT.load(RT.java:453)
  at clojure.lang.RT.load(RT.java:419)
  at clojure.core$load$fn__5677.invoke(core.clj:5893)
  at clojure.core$load.invokeStatic(core.clj:5892)
  at clojure.core$load.doInvoke(core.clj:5876)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at clojure.core$load_one.invokeStatic(core.clj:5697)
  at clojure.core$load_one.invoke(core.clj:5692)
  at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
  at clojure.core$load_lib.invokeStatic(core.clj:5736)
  at clojure.core$load_lib.doInvoke(core.clj:5717)
  at clojure.lang.RestFn.applyTo(RestFn.java:142)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$load_libs.invokeStatic(core.clj:5774)
  at clojure.core$load_libs.doInvoke(core.clj:5758)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$require.invokeStatic(core.clj:5796)
  at clojure.core$require.doInvoke(core.clj:5796)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at heartbeat.core$eval3796$loading__5569__auto____3797.invoke(core.clj:1)
  at heartbeat.core$eval3796.invokeStatic(core.clj:1)
  at heartbeat.core$eval3796.invoke(core.clj:1)
  at clojure.lang.Compiler.eval(Compiler.java:6927)
  at clojure.lang.Compiler.eval(Compiler.java:6916)
  at clojure.lang.Compiler.load(Compiler.java:7379)
  at clojure.lang.RT.loadResourceScript(RT.java:372)
  at clojure.lang.RT.loadResourceScript(RT.java:363)
  at clojure.lang.RT.load(RT.java:453)
  at clojure.lang.RT.load(RT.java:419)
  at clojure.core$load$fn__5677.invoke(core.clj:5893)
  at clojure.core$load.invokeStatic(core.clj:5892)
  at clojure.core$load.doInvoke(core.clj:5876)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at clojure.core$load_one.invokeStatic(core.clj:5697)
  at clojure.core$load_one.invoke(core.clj:5692)
  at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
  at clojure.core$load_lib.invokeStatic(core.clj:5736)
  at clojure.core$load_lib.doInvoke(core.clj:5717)
  at clojure.lang.RestFn.applyTo(RestFn.java:142)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$load_libs.invokeStatic(core.clj:5774)
  at clojure.core$load_libs.doInvoke(core.clj:5758)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$require.invokeStatic(core.clj:5796)
  at clojure.core$require.doInvoke(core.clj:5796)
  at clojure.lang.RestFn.invoke(RestFn.java:457)
  at heartbeat.ring$eval3790$loading__5569__auto____3791.invoke(ring.clj:1)
  at heartbeat.ring$eval3790.invokeStatic(ring.clj:1)
  at heartbeat.ring$eval3790.invoke(ring.clj:1)
  at clojure.lang.Compiler.eval(Compiler.java:6927)
  at clojure.lang.Compiler.eval(Compiler.java:6916)
  at clojure.lang.Compiler.load(Compiler.java:7379)
  at clojure.lang.RT.loadResourceScript(RT.java:372)
  at clojure.lang.RT.loadResourceScript(RT.java:363)
  at clojure.lang.RT.load(RT.java:453)
  at clojure.lang.RT.load(RT.java:419)
  at clojure.core$load$fn__5677.invoke(core.clj:5893)
  at clojure.core$load.invokeStatic(core.clj:5892)
  at clojure.core$load.doInvoke(core.clj:5876)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at clojure.core$load_one.invokeStatic(core.clj:5697)
  at clojure.core$load_one.invoke(core.clj:5692)
  at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
  at clojure.core$load_lib.invokeStatic(core.clj:5736)
  at clojure.core$load_lib.doInvoke(core.clj:5717)
  at clojure.lang.RestFn.applyTo(RestFn.java:142)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$load_libs.invokeStatic(core.clj:5774)
  at clojure.core$load_libs.doInvoke(core.clj:5758)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$require.invokeStatic(core.clj:5796)
  at clojure.core$require.doInvoke(core.clj:5796)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at event_data_live_stream.server$eval1538$loading__5569__auto____1539.invoke(server.clj:1)
  at event_data_live_stream.server$eval1538.invokeStatic(server.clj:1)
  at event_data_live_stream.server$eval1538.invoke(server.clj:1)
  at clojure.lang.Compiler.eval(Compiler.java:6927)
  at clojure.lang.Compiler.eval(Compiler.java:6916)
  at clojure.lang.Compiler.load(Compiler.java:7379)
  at clojure.lang.RT.loadResourceScript(RT.java:372)
  at clojure.lang.RT.loadResourceScript(RT.java:363)
  at clojure.lang.RT.load(RT.java:453)
  at clojure.lang.RT.load(RT.java:419)
  at clojure.core$load$fn__5677.invoke(core.clj:5893)
  at clojure.core$load.invokeStatic(core.clj:5892)
  at clojure.core$load.doInvoke(core.clj:5876)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at clojure.core$load_one.invokeStatic(core.clj:5697)
  at clojure.core$load_one.invoke(core.clj:5692)
  at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
  at clojure.core$load_lib.invokeStatic(core.clj:5736)
  at clojure.core$load_lib.doInvoke(core.clj:5717)
  at clojure.lang.RestFn.applyTo(RestFn.java:142)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$load_libs.invokeStatic(core.clj:5774)
  at clojure.core$load_libs.doInvoke(core.clj:5758)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$require.invokeStatic(core.clj:5796)
  at clojure.core$require.doInvoke(core.clj:5796)
  at clojure.lang.RestFn.invoke(RestFn.java:436)
  at event_data_live_stream.fetch$eval324$loading__5569__auto____325.invoke(fetch.clj:1)
  at event_data_live_stream.fetch$eval324.invokeStatic(fetch.clj:1)
  at event_data_live_stream.fetch$eval324.invoke(fetch.clj:1)
  at clojure.lang.Compiler.eval(Compiler.java:6927)
  at clojure.lang.Compiler.eval(Compiler.java:6916)
  at clojure.lang.Compiler.load(Compiler.java:7379)
  at clojure.lang.RT.loadResourceScript(RT.java:372)
  at clojure.lang.RT.loadResourceScript(RT.java:363)
  at clojure.lang.RT.load(RT.java:453)
  at clojure.lang.RT.load(RT.java:419)
  at clojure.core$load$fn__5677.invoke(core.clj:5893)
  at clojure.core$load.invokeStatic(core.clj:5892)
  at clojure.core$load.doInvoke(core.clj:5876)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at clojure.core$load_one.invokeStatic(core.clj:5697)
  at clojure.core$load_one.invoke(core.clj:5692)
  at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
  at clojure.core$load_lib.invokeStatic(core.clj:5736)
  at clojure.core$load_lib.doInvoke(core.clj:5717)
  at clojure.lang.RestFn.applyTo(RestFn.java:142)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$load_libs.invokeStatic(core.clj:5774)
  at clojure.core$load_libs.doInvoke(core.clj:5758)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$require.invokeStatic(core.clj:5796)
  at clojure.core$require.doInvoke(core.clj:5796)
  at clojure.lang.RestFn.invoke(RestFn.java:421)
  at event_data_live_stream.core$eval20$loading__5569__auto____21.invoke(core.clj:1)
  at event_data_live_stream.core$eval20.invokeStatic(core.clj:1)
  at event_data_live_stream.core$eval20.invoke(core.clj:1)
  at clojure.lang.Compiler.eval(Compiler.java:6927)
  at clojure.lang.Compiler.eval(Compiler.java:6916)
  at clojure.lang.Compiler.load(Compiler.java:7379)
  at clojure.lang.RT.loadResourceScript(RT.java:372)
  at clojure.lang.RT.loadResourceScript(RT.java:363)
  at clojure.lang.RT.load(RT.java:453)
  at clojure.lang.RT.load(RT.java:419)
  at clojure.core$load$fn__5677.invoke(core.clj:5893)
  at clojure.core$load.invokeStatic(core.clj:5892)
  at clojure.core$load.doInvoke(core.clj:5876)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at clojure.core$load_one.invokeStatic(core.clj:5697)
  at clojure.core$load_one.invoke(core.clj:5692)
  at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
  at clojure.core$load_lib.invokeStatic(core.clj:5736)
  at clojure.core$load_lib.doInvoke(core.clj:5717)
  at clojure.lang.RestFn.applyTo(RestFn.java:142)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$load_libs.invokeStatic(core.clj:5774)
  at clojure.core$load_libs.doInvoke(core.clj:5758)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.core$apply.invokeStatic(core.clj:648)
  at clojure.core$require.invokeStatic(core.clj:5796)
  at clojure.core$require.doInvoke(core.clj:5796)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at user$eval5$fn__7.invoke(form-init5984972104985917779.clj:1)
  at user$eval5.invokeStatic(form-init5984972104985917779.clj:1)
  at user$eval5.invoke(form-init5984972104985917779.clj:1)
  at clojure.lang.Compiler.eval(Compiler.java:6927)
  at clojure.lang.Compiler.eval(Compiler.java:6917)
  at clojure.lang.Compiler.load(Compiler.java:7379)
  at clojure.lang.Compiler.loadFile(Compiler.java:7317)
  at clojure.main$load_script.invokeStatic(main.clj:275)
  at clojure.main$init_opt.invokeStatic(main.clj:277)
  at clojure.main$init_opt.invoke(main.clj:277)
  at clojure.main$initialize.invokeStatic(main.clj:308)
  at clojure.main$null_opt.invokeStatic(main.clj:342)
  at clojure.main$null_opt.invoke(main.clj:339)
  at clojure.main$main.invokeStatic(main.clj:421)
  at clojure.main$main.doInvoke(main.clj:384)
  at clojure.lang.RestFn.invoke(RestFn.java:421)
  at clojure.lang.Var.invoke(Var.java:383)
  at clojure.lang.AFn.applyToHelper(AFn.java:156)
  at clojure.lang.Var.applyTo(Var.java:700)
  at clojure.main.main(main.java:37)
```
